export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/login/index',
    'pages/onboarding/index',
    'pages/records/index',
    'pages/history/index',
    'pages/health-insights/index',
    'pages/progress-photos/index',
    'pages/food-photo-workflow/index',
    'pages/workouts/index',
    'pages/exercise-insights/index',
    'pages/nutrition/index',
    'pages/nutrition-insights/index',
    'pages/food-catalog/index',
    'pages/plans/index',
    'pages/ai-explanations/index',
    'pages/privacy/index',
  ],
  window: {
    backgroundColor: '#F2F6F5',
    backgroundTextStyle: 'dark',
    navigationStyle: 'custom',
  },
})
