export const muscleModelVersion = 'ilens-muscle-model-v1' as const

export const muscleRegionIds = ['chest', 'back', 'shoulders_arms', 'legs_glutes', 'core'] as const

export const mappableMuscleIds = [
  'chest_upper',
  'chest_middle',
  'chest_lower',
  'latissimus_dorsi',
  'trapezius',
  'rhomboids',
  'teres_major',
  'teres_minor',
  'erector_spinae',
  'deltoid_anterior',
  'deltoid_lateral',
  'deltoid_posterior',
  'biceps_brachii',
  'triceps_brachii',
  'brachialis',
  'forearms',
  'gluteus_maximus',
  'gluteus_medius',
  'quadriceps',
  'hamstrings',
  'adductors',
  'gastrocnemius',
  'soleus',
  'rectus_abdominis',
  'obliques',
] as const

export const muscleIds = [...mappableMuscleIds, 'core_global'] as const

export const muscleNodeTypes = ['muscle_group', 'aggregate'] as const
export const muscleBodyViews = ['front', 'back'] as const

export const muscleModelRegions = [
  { id: 'chest', nameZh: '胸', displayOrder: 1 },
  { id: 'back', nameZh: '背', displayOrder: 2 },
  { id: 'shoulders_arms', nameZh: '肩 / 手臂', displayOrder: 3 },
  { id: 'legs_glutes', nameZh: '腿 / 臀', displayOrder: 4 },
  { id: 'core', nameZh: '腹 / 核心', displayOrder: 5 },
] as const

export const muscleModelMuscles = [
  {
    id: 'chest_upper',
    regionId: 'chest',
    nameZh: '上胸',
    nodeType: 'muscle_group',
    bodyViews: ['front'],
    displayOrder: 1,
  },
  {
    id: 'chest_middle',
    regionId: 'chest',
    nameZh: '中胸',
    nodeType: 'muscle_group',
    bodyViews: ['front'],
    displayOrder: 2,
  },
  {
    id: 'chest_lower',
    regionId: 'chest',
    nameZh: '下胸',
    nodeType: 'muscle_group',
    bodyViews: ['front'],
    displayOrder: 3,
  },
  {
    id: 'latissimus_dorsi',
    regionId: 'back',
    nameZh: '背阔肌',
    nodeType: 'muscle_group',
    bodyViews: ['back'],
    displayOrder: 1,
  },
  {
    id: 'trapezius',
    regionId: 'back',
    nameZh: '斜方肌',
    nodeType: 'muscle_group',
    bodyViews: ['back'],
    displayOrder: 2,
  },
  {
    id: 'rhomboids',
    regionId: 'back',
    nameZh: '菱形肌',
    nodeType: 'muscle_group',
    bodyViews: ['back'],
    displayOrder: 3,
  },
  {
    id: 'teres_major',
    regionId: 'back',
    nameZh: '大圆肌',
    nodeType: 'muscle_group',
    bodyViews: ['back'],
    displayOrder: 4,
  },
  {
    id: 'teres_minor',
    regionId: 'back',
    nameZh: '小圆肌',
    nodeType: 'muscle_group',
    bodyViews: ['back'],
    displayOrder: 5,
  },
  {
    id: 'erector_spinae',
    regionId: 'back',
    nameZh: '竖脊肌',
    nodeType: 'muscle_group',
    bodyViews: ['back'],
    displayOrder: 6,
  },
  {
    id: 'deltoid_anterior',
    regionId: 'shoulders_arms',
    nameZh: '三角肌前束',
    nodeType: 'muscle_group',
    bodyViews: ['front'],
    displayOrder: 1,
  },
  {
    id: 'deltoid_lateral',
    regionId: 'shoulders_arms',
    nameZh: '三角肌中束',
    nodeType: 'muscle_group',
    bodyViews: ['front', 'back'],
    displayOrder: 2,
  },
  {
    id: 'deltoid_posterior',
    regionId: 'shoulders_arms',
    nameZh: '三角肌后束',
    nodeType: 'muscle_group',
    bodyViews: ['back'],
    displayOrder: 3,
  },
  {
    id: 'biceps_brachii',
    regionId: 'shoulders_arms',
    nameZh: '肱二头肌',
    nodeType: 'muscle_group',
    bodyViews: ['front'],
    displayOrder: 4,
  },
  {
    id: 'triceps_brachii',
    regionId: 'shoulders_arms',
    nameZh: '肱三头肌',
    nodeType: 'muscle_group',
    bodyViews: ['back'],
    displayOrder: 5,
  },
  {
    id: 'brachialis',
    regionId: 'shoulders_arms',
    nameZh: '肱肌',
    nodeType: 'muscle_group',
    bodyViews: ['front'],
    displayOrder: 6,
  },
  {
    id: 'forearms',
    regionId: 'shoulders_arms',
    nameZh: '前臂',
    nodeType: 'muscle_group',
    bodyViews: ['front', 'back'],
    displayOrder: 7,
  },
  {
    id: 'gluteus_maximus',
    regionId: 'legs_glutes',
    nameZh: '臀大肌',
    nodeType: 'muscle_group',
    bodyViews: ['back'],
    displayOrder: 1,
  },
  {
    id: 'gluteus_medius',
    regionId: 'legs_glutes',
    nameZh: '臀中肌',
    nodeType: 'muscle_group',
    bodyViews: ['front', 'back'],
    displayOrder: 2,
  },
  {
    id: 'quadriceps',
    regionId: 'legs_glutes',
    nameZh: '股四头肌',
    nodeType: 'muscle_group',
    bodyViews: ['front'],
    displayOrder: 3,
  },
  {
    id: 'hamstrings',
    regionId: 'legs_glutes',
    nameZh: '腘绳肌',
    nodeType: 'muscle_group',
    bodyViews: ['back'],
    displayOrder: 4,
  },
  {
    id: 'adductors',
    regionId: 'legs_glutes',
    nameZh: '内收肌',
    nodeType: 'muscle_group',
    bodyViews: ['front'],
    displayOrder: 5,
  },
  {
    id: 'gastrocnemius',
    regionId: 'legs_glutes',
    nameZh: '腓肠肌',
    nodeType: 'muscle_group',
    bodyViews: ['back'],
    displayOrder: 6,
  },
  {
    id: 'soleus',
    regionId: 'legs_glutes',
    nameZh: '比目鱼肌',
    nodeType: 'muscle_group',
    bodyViews: ['back'],
    displayOrder: 7,
  },
  {
    id: 'rectus_abdominis',
    regionId: 'core',
    nameZh: '腹直肌',
    nodeType: 'muscle_group',
    bodyViews: ['front'],
    displayOrder: 1,
  },
  {
    id: 'obliques',
    regionId: 'core',
    nameZh: '腹斜肌',
    nodeType: 'muscle_group',
    bodyViews: ['front'],
    displayOrder: 2,
  },
  {
    id: 'core_global',
    regionId: 'core',
    nameZh: '核心整体',
    nodeType: 'aggregate',
    bodyViews: ['front', 'back'],
    displayOrder: 3,
  },
] as const

export const muscleModelCatalog = {
  version: muscleModelVersion,
  regions: muscleModelRegions,
  muscles: muscleModelMuscles,
} as const
